config/routes.rb
Rails.application.routes.draw do

  get 'auth/facebook/callback', to: 'sessions#create'
  post 'auth/android', to: 'sessions#auth', :defaults => { :format => :json }
  post 'teams', to: 'teams#create', :defaults => { :format => :json }

  resources :monsters

  root 'application#login'

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  enum mtype: [:fire, :water, :earth, :electric, :wind]

  belongs_to :user
  belongs_to :team

  validates_presence_of :user

  # Get the strength of the monster.
  def strength
    Monster.mtypes.key(
      (Monster.mtypes[mtype] - 1) % Monster.mtypes.count
    )
  end

  # Get the weakness of the monster.
  def weakness
    Monster.mtypes.key(
      (Monster.mtypes[mtype] + 1) % Monster.mtypes.count
    )
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :user
  has_many :monsters
  validates_length_of :monsters, is: 3
  accepts_nested_attributes_for :monsters
end

app/models/user.rb
class User < ActiveRecord::Base
  cattr_accessor :plain_password
  has_many :teams
  has_many :monsters

  validates_length_of :teams, maximum: 3
  validates_length_of :monsters, maximum: 20

  class << self
    def encrypt(str)
      Digest::SHA2.hexdigest(str)
    end

    def omniauth(auth)
      user = User.find_or_initialize_by(uid: auth.uid)
      return user if user.id
      user.name = auth.info.name
      user.fb_token = auth.credentials.token
      user.salt = SecureRandom.base64(8)
      user.plain_password = SecureRandom.base64(8)
      user.password = encrypt(user.salt + user.plain_password)
      user.save!
      return user
    end

    def auth(id, password)
      user = User.find_by(id: id)
      user.token = SecureRandom.urlsafe_base64
      user.save
      return user if user && encrypt(user.salt + password) == user.password
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def login
    redirect_to "/auth/facebook"
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  include ApplicationHelper

  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  before_action :enforce_auth

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = cur_user.monsters
    @monsters.order(params[:order_by]) if params[:order_by] && ["name", "power", "mtype"].include?(params[:order_by])
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)
    @monster.user = cur_user
    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :power, :mtype)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def create
    user = User.omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to monsters_url, notice: web_login_notice(user)
  end

  # For android authentication
  def auth
    user = User.auth(params[:id], params[:password])
    if user
      render json: user.to_json(only: :token)
    else
      render json: "Incorrect data"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_user
    return User.find_by(id: session[:user_id]) if session[:user_id]
    return User.find_by(token: params[:token]) if params[:token]
    return nil
  end

  def cur_user
    @cur_user ||= get_user
  end

  def enforce_auth
    unless cur_user
      if request.format == 'json'
        render json: "Must be logged in"
      else
        redirect_to "/auth/facebook" unless cur_user
      end
    end
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def web_login_notice(user)
    if user.plain_password
      return t(:successful_register) + "id: #{user.id} password: #{user.plain_password}"
    else
      return t(:successful_login)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubymon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :mtype %><br>
    <%= f.select(:mtype, Monster.mtypes.keys.map {|mtype| [mtype.titleize,mtype]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monsters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Power</th>
      <th>Mtype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.power %></td>
        <td><%= monster.mtype %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monster', new_monster_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Power:</strong>
  <%= @monster.power %>
</p>

<p>
  <strong>Mtype:</strong>
  <%= @monster.mtype %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>